// <auto-generated />
using System;
using Etutlist.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Etutlist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111114857_UpdateFakulteTelafiAyarlariConfig")]
    partial class UpdateFakulteTelafiAyarlariConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Etutlist.Models.AylikYedekListesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ay")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("Yil", "Ay", "PersonelId")
                        .IsUnique();

                    b.ToTable("AylikYedekListeleri");
                });

            modelBuilder.Entity("Etutlist.Models.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("Etutlist.Models.DersProgrami", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersGunu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DersId")
                        .HasColumnType("int");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersSaati")
                        .HasColumnType("int");

                    b.Property<int>("FakulteId")
                        .HasColumnType("int");

                    b.Property<int>("HocaId")
                        .HasColumnType("int");

                    b.Property<int>("KisimNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("FakulteId");

                    b.HasIndex("HocaId");

                    b.ToTable("DersProgrami");
                });

            modelBuilder.Entity("Etutlist.Models.Etut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PersonelAd")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("PersonelRutbe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SinifNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("Etutler", (string)null);
                });

            modelBuilder.Entity("Etutlist.Models.Fakulte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fakulteler");
                });

            modelBuilder.Entity("Etutlist.Models.FakulteTelafiAyarlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FakulteId")
                        .HasColumnType("int");

                    b.Property<int>("MaxKisimNo")
                        .HasColumnType("int");

                    b.Property<int>("MinKisimNo")
                        .HasColumnType("int");

                    b.Property<int>("TelafiBaslamaSaati")
                        .HasColumnType("int");

                    b.Property<string>("TelafiYapilamayacakGun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FakulteId");

                    b.ToTable("FakulteTelafiAyarlari");
                });

            modelBuilder.Entity("Etutlist.Models.Hoca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("FakulteId")
                        .HasColumnType("int");

                    b.Property<string>("Rutbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FakulteId");

                    b.ToTable("Hocalar");
                });

            modelBuilder.Entity("Etutlist.Models.HocaDers", b =>
                {
                    b.Property<int>("HocaId")
                        .HasColumnType("int");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.HasKey("HocaId", "DersId");

                    b.HasIndex("DersId");

                    b.ToTable("HocaDersler");
                });

            modelBuilder.Entity("Etutlist.Models.Mazeret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Baslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Bitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("Mazeretler", (string)null);
                });

            modelBuilder.Entity("Etutlist.Models.OzelGun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OzelGunler", (string)null);
                });

            modelBuilder.Entity("Etutlist.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("HaftaIciSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("OzelGunSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PazarSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Rutbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YedekSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Personeller", (string)null);
                });

            modelBuilder.Entity("Etutlist.Models.TelafiDers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("BaslangicSaat")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaat")
                        .HasColumnType("time");

                    b.Property<bool>("CiktiAlindi")
                        .HasColumnType("bit");

                    b.Property<int>("DersProgramiId")
                        .HasColumnType("int");

                    b.Property<int>("FakulteId")
                        .HasColumnType("int");

                    b.Property<int?>("HocaId")
                        .HasColumnType("int");

                    b.Property<int?>("KisimNo")
                        .HasColumnType("int");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("bit");

                    b.Property<string>("TelafiNedeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TelafiTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelafiTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YedekHocaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DersProgramiId");

                    b.HasIndex("FakulteId");

                    b.HasIndex("HocaId");

                    b.HasIndex("YedekHocaId");

                    b.ToTable("TelafiDersler");
                });

            modelBuilder.Entity("Etutlist.Models.AylikYedekListesi", b =>
                {
                    b.HasOne("Etutlist.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Etutlist.Models.DersProgrami", b =>
                {
                    b.HasOne("Etutlist.Models.Ders", "Ders")
                        .WithMany("DersProgramlari")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Etutlist.Models.Fakulte", "Fakulte")
                        .WithMany("DersProgramlari")
                        .HasForeignKey("FakulteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Etutlist.Models.Hoca", "Hoca")
                        .WithMany("Dersler")
                        .HasForeignKey("HocaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Fakulte");

                    b.Navigation("Hoca");
                });

            modelBuilder.Entity("Etutlist.Models.Etut", b =>
                {
                    b.HasOne("Etutlist.Models.Personel", "Personel")
                        .WithMany("Etutler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Etutlist.Models.FakulteTelafiAyarlari", b =>
                {
                    b.HasOne("Etutlist.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("Etutlist.Models.Hoca", b =>
                {
                    b.HasOne("Etutlist.Models.Fakulte", "Fakulte")
                        .WithMany("Hocalar")
                        .HasForeignKey("FakulteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("Etutlist.Models.HocaDers", b =>
                {
                    b.HasOne("Etutlist.Models.Ders", "Ders")
                        .WithMany("DersHocalari")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Etutlist.Models.Hoca", "Hoca")
                        .WithMany("HocaDersler")
                        .HasForeignKey("HocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Hoca");
                });

            modelBuilder.Entity("Etutlist.Models.Mazeret", b =>
                {
                    b.HasOne("Etutlist.Models.Personel", "Personel")
                        .WithMany("Mazeretler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Etutlist.Models.TelafiDers", b =>
                {
                    b.HasOne("Etutlist.Models.DersProgrami", "DersProgrami")
                        .WithMany("TelafiDersler")
                        .HasForeignKey("DersProgramiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Etutlist.Models.Fakulte", "Fakulte")
                        .WithMany("TelafiDersler")
                        .HasForeignKey("FakulteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Etutlist.Models.Hoca", null)
                        .WithMany("TelafiDersler")
                        .HasForeignKey("HocaId");

                    b.HasOne("Etutlist.Models.Hoca", "YedekHoca")
                        .WithMany()
                        .HasForeignKey("YedekHocaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DersProgrami");

                    b.Navigation("Fakulte");

                    b.Navigation("YedekHoca");
                });

            modelBuilder.Entity("Etutlist.Models.Ders", b =>
                {
                    b.Navigation("DersHocalari");

                    b.Navigation("DersProgramlari");
                });

            modelBuilder.Entity("Etutlist.Models.DersProgrami", b =>
                {
                    b.Navigation("TelafiDersler");
                });

            modelBuilder.Entity("Etutlist.Models.Fakulte", b =>
                {
                    b.Navigation("DersProgramlari");

                    b.Navigation("Hocalar");

                    b.Navigation("TelafiDersler");
                });

            modelBuilder.Entity("Etutlist.Models.Hoca", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("HocaDersler");

                    b.Navigation("TelafiDersler");
                });

            modelBuilder.Entity("Etutlist.Models.Personel", b =>
                {
                    b.Navigation("Etutler");

                    b.Navigation("Mazeretler");
                });
#pragma warning restore 612, 618
        }
    }
}
